# HTML 외에 JS, CSS 파일이 포함된 폴더 경로를 명시
sonar.sources=.

# JavaScript 및 CSS 분석 엔진이 작동하도록 확장자 매핑 강제
sonar.javascript.file.suffixes=.js,.jsx
sonar.css.file.suffixes=.css

# (선택) 너무 큰 라이브러리 파일이라 인덱싱에서 누락되는 것을 방지하기 위해 
# 검증할 파일들을 명시적으로 포함시킬 때 사용합니다.
sonar.inclusions=**/*.html, **/pdf.js, **/pdf.worker.js, **/pdf_viewer.css
