# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow helps you trigger a SonarQube analysis of your code and populates
# GitHub Code Scanning alerts with the vulnerabilities found.
# (this feature is available starting from SonarQube 9.7, Developer Edition and above)

name: SonarCloud Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      # 수동 파일 분석을 진행하기 전에 소스코드를 가상 환경으로 체크아웃하는 필수 단계입니다.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 전체 히스토리를 가져와야 일조권/코드 추적이 정확해집니다.

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
          # secrets에 등록하기 귀찮다면 아래처럼 직접 주소를 적어두셔도 무방합니다.
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=whwocom_test
            -Dsonar.sources=.
            -Dsonar.inclusions=**/*.html,**/pdf.js,**/pdf.worker.js,**/pdf_viewer.css
            -Dsonar.javascript.maxFileSize=20
